---
title: "Depicting the Casualty Figures of the Holocaust"
subtitle: "A discourse on the ethics behind the data"
author: 
  - Raghav Bhatia
thanks: "Code and shinyapp are available at: https://github.com/1raghav-bhatia/shiny-holo.git, https://1raghavbhatia.shinyapps.io/holocaust_data/"
date: April 2, 2024
date-format: long
toc: true
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(shiny)
library(tidyverse)
library(ggplot2)
library(readr)

```


# Essay

The holocaust is one of the most painful periods of human history. It lead to countless deaths and enumerable families losing their loved ones due to its atrocities. While today we can access the records of victims and casualties of the Holocaust and study their plight within detention camps, we must recognize that these records are but a small measurement of the victims' total suffering. 

We start by recognizing the need to study the casualty data in order to paint a picture of what happened in these camps. While incomplete, the data record of casualties is the best possible piece of information we have to quantify the injustice of the holocaust. This data gives us information about victim nationality and religion, thereby pinpointing the regions that were most targeted by the holocaust. This gives us a good indication of the regions worst affected by the holocaust, thereby helping the descendants of holocaust victims figure out the fate of their great-grandparents. The obvious fact that much of this data comes from Nazi war records does indicate that it could be incomplete or only contain facts which the Nazis required for their purposes. Despite that, this data is the most accurate record of the victims, and therefore can provide immense value for the descendants of Holocaust victims.

While collecting data on the casualties within Auschwitz, its important to realize that while it might provide valuable insights into the severity of the Holocaust by location, it does reduce the stories of millions of victims to simply their casualty status. While providing the casualty data, we've probably used the very same data that the Nazi's used, albeit for a different purpose. The fact that we are looking at the same data points and using the same mathematical and statistical techniques which reduce deaths to data points is indicative of the fact that we are obscuring a lot of information about the victims in question. In line with [@citeBouie], we have to consider how our tools abstract away the humane aspects of the data, and the "extent to which the tools of abstraction are themselves tied up in the history" of the Holocaust. 

It is important to emphasize that the data we are using does abstract away much of the suffering suffered by the victims. Studies which may use the data to quantify the suffering of Auschwitz on the basis of number of deaths by region will completely miss the fact that the data was collected by the Nazi regime and will definitely omit aspects related to true suffering. We do not know how much suffering is hidden away by the lack of data on victims, but we do recognize that alternative sources such as victim's families testimonies need to be taken into account while collecting any amount of data about the victim.

In closing, we note that while data about victims of the Holocaust opens up a new frontier in research within the "digital humanities", overuse of the data to make wild assertions will lead to a miss-representation of the plight of victims. The data needs to be used knowing that much of it was just aspects recorded by the Nazi regime, and aspects actually relating to human plight was deliberately omitted as the regime had no use for it.

\newpage

# References


